### ISSUE TITLE
Error in Whole genome bedmethyl processing step

### ISSUE THREAD

**Issue by BeatrizFaustino** [SoundAg/sounDMR#54] opened 2023-11-07 01:41 UTC
When executing the Whole genome bedmethyl processing step, the following error appears: Error in file (input_file, "r") Unable to open connection.
Warning message: In file (input_file, "r"): could not open the file 'WaterControl_2_methyl.bed': No such file or directory.

What would be the cause of this problem?

**Comment by kprabhu-soundag** [comment] 2023-11-07 18:20
From the error it looks like it is trying to find 'WaterControl_2_methyl.bed' but it is unable to find it because it is probably not in the directory. 

This is one of the sample data we published so you have to download, make it available in your local folder and point it to the directory before running the pipeline. refer to the documentation here [https://github.com/SoundAg/sounDMR/blob/main/README.md]

**Comment by BeatrizFaustino** [comment] 2023-11-09 18:44
Thank you for the information, now I have another error, can you help me?
1: In dir.create(file.path(input_dir, paste0("chr_", chromosome))) :
   Unable to create directory 'WaterControl_2_methyl.bed\chr_NC_003070.9', reason 'No such file or directory'
2: In file(output_file, "w") :
   could not open the file 'WaterControl_2_methyl.bed/chr_NC_003070.9/WaterControl_2_methyl.bed': No such file or directory

**Comment by tcairns-soundag** [comment] 2023-11-10 19:55
This is a bug in our split_by_chromosome function that we will be fixing in our next build of the package. Currently `split_by_chromosome()` takes an absolute path, but the DMR_analysis_workflow is passing in just the filename, which leads to this issue.

**Comment by BeatrizFaustino** [comment] 2023-11-17 19:24
Thanks for the answer! Can the geneco file be the GFF annotation file? or should it be another file?

**Comment by BeatrizFaustino** [comment] 2023-11-18 22:54
I have this error when trying to perform methyl_summary <- create_methyl_summary(dmr_obj, control = 'C', treated = 'T',
                                         additional_summary_cols = list(c('sd', 'Group'))):

Error in `[.data.frame`(GenePercentPlant, , id) :
   selected undefined columns

Can you help me please?

**Comment by kprabhu-soundag** [comment] 2023-11-20 17:35
> Thanks for the answer! Can the geneco file be the GFF annotation file? or should it be another file?

Hi, The Geneco file needs to have a certain format that should at least have the columns shown in the screenshot. Please refer to the documentation for more information. 
![image](https://github.com/SoundAg/sounDMR/assets/80559286/49a342f8-fbe2-4441-90cf-bdc61db35ad3)

**Comment by tcairns-soundag** [comment] 2023-11-20 20:14
> I have this error when trying to perform methyl_summary <- create_methyl_summary(dmr_obj, control = 'C', treated = 'T', additional_summary_cols = list(c('sd', 'Group'))):
> 
> Error in `[.data.frame`(GenePercentPlant, , id) : selected undefined columns
> 
> Can you help me please?

For this error can you send me the top 5 lines of the dmr_obj$GenePercentPlant? I'm wondering if it is related to the Geneco file in the previous question, but I won't know for sure without seeing a subset of the data.

**Comment by BeatrizFaustino** [comment] 2023-11-21 11:27
Hi, I'm not using a geneco file. This file is optional, right? I think that's why I don't have dmr_obj$GenePercentPlant, just dmr_obj. Is the geneco file to create the zoomframe mandatory to find the DMRs?

**Comment by tcairns-soundag** [comment] 2023-11-22 17:52
That is correct that the Geneco file is not required. Can you send me the output of `head(dmr_obj$LongPercent)` and `head(dmr_obj$experimental_design_df)` so I can try to reproduce the error?

**Comment by BeatrizFaustino** [comment] 2023-11-23 12:19
Of course I can! I'm using the example data for the first time.

> head(dmr_obj$LongPercent)
# A tibble: 6 × 9
# Groups:   Gene, Zeroth_pos, Plant, Position, CX, Strand, Group [6]
  Gene        Zeroth_pos Plant Position CX    Strand Group Chromosome  Percent
  <chr>            <int> <chr>    <int> <chr> <chr>  <chr> <chr>         <dbl>
1 NC_003070.9     220910 NA      220910 CG    -      NA    NC_003070.9    5   
2 NC_003070.9     220913 NA      220913 CG    -      NA    NC_003070.9    2.5 
3 NC_003070.9     220916 NA      220916 CHH   -      NA    NC_003070.9    2.25
4 NC_003070.9     220925 NA      220925 CG    -      NA    NC_003070.9    5   
5 NC_003070.9     222062 NA      222062 CG    +      NA    NC_003070.9    8.25
6 NC_003070.9     222284 NA      222284 CHG   +      NA    NC_003070.9    8.25
> head(dmr_obj$experimental_design_df)
  ID                      Library Individual Treatment Group Zeb_Concentration     Plant
1 S1 ZEB_EXP_3_Pool3_R1.barcode06   Zeb100_8    Zeb100     T               100  Zeb100_8
2 S2 ZEB_EXP_3_Pool4_R1.barcode07    Water_8     Water     C                 0   Water_8
3 S3 ZEB_EXP_3_POOL6_R2.barcode12  Zeb_100_2    Zeb100     T               100 Zeb_100_2
4 S4 ZEB_EXP_3_POOL5_R1.barcode09    Water_2     Water     C                 0   Water_2
  Individual_Name
1        Zeb100_8
2         Water_8
3       Zeb_100_2
4         Water_2

**Comment by BeatrizFaustino** [comment] 2023-11-23 12:24
Of course I can! I'm using the example data for the first time.

> head(dmr_obj$LongPercent)
A tibble: 6 × 9
 Groups:   Gene, Zeroth_pos, Plant, Position, CX, Strand, Group [6]
  Gene        Zeroth_pos Plant Position CX    Strand Group Chromosome  Percent
  <chr>            <int> <chr>    <int> <chr> <chr>  <chr> <chr>         <dbl>
1 NC_003070.9     220910 NA      220910 CG    -      NA    NC_003070.9    5   
2 NC_003070.9     220913 NA      220913 CG    -      NA    NC_003070.9    2.5 
3 NC_003070.9     220916 NA      220916 CHH   -      NA    NC_003070.9    2.25
4 NC_003070.9     220925 NA      220925 CG    -      NA    NC_003070.9    5   
5 NC_003070.9     222062 NA      222062 CG    +      NA    NC_003070.9    8.25
6 NC_003070.9     222284 NA      222284 CHG   +      NA    NC_003070.9    8.25

> head(dmr_obj$experimental_design_df)
  ID                      Library Individual Treatment Group Zeb_Concentration     Plant
1 S1 ZEB_EXP_3_Pool3_R1.barcode06   Zeb100_8    Zeb100     T               100  Zeb100_8
2 S2 ZEB_EXP_3_Pool4_R1.barcode07    Water_8     Water     C                 0   Water_8
3 S3 ZEB_EXP_3_POOL6_R2.barcode12  Zeb_100_2    Zeb100     T               100 Zeb_100_2
4 S4 ZEB_EXP_3_POOL5_R1.barcode09    Water_2     Water     C                 0   Water_2
  Individual_Name
1        Zeb100_8
2         Water_8
3       Zeb_100_2
4         Water_2

**Comment by BeatrizFaustino** [comment] 2023-11-23 12:37
Sorry,  havia fechado o problema por engano, agora reabri

**Comment by BeatrizFaustino** [comment] 2023-11-23 12:37
Sorry, I closed the issue by mistake, now I reopened it

**Comment by BeatrizFaustino** [comment] 2023-11-23 12:39
![Sem título](https://github.com/SoundAg/sounDMR/assets/100097471/91a7d048-4700-423a-9b41-acce0df950c8)

**Comment by kprabhu-soundag** [comment] 2023-12-04 18:55
Hi @BeatrizFaustino , First off, the sample data provided is not meant to run through the whole genome pipeline; that said it can be used as a test run for sure but the results will be not be very accurate - especially the zeroth position column. 

Now the issue is related to the Plant column having NAs. For the same reason, it not able to produce the Gene Percent Plant and is leading to the error. In order to reproduce the column, I will need the .R script and R image and R env details. Until then we won't be able to find the root cause of the issue.

**Comment by kprabhu-soundag** [comment] 2024-03-21 20:34
closing this issue since we haven't seen any recent activity or any comments.

**Closed by kprabhu-soundag** 2024-03-21 20:34 UTC

**Comment by PraddyumnaR** [comment] 2024-08-19 04:23
Hi I am facing a issue in Whole genome analysis 
Chr1    1115    1116    CHG     10      +       1115    1116    255     10      80.00   CHG
Chr1    1117    1118    CHG     14      -       1117    1118    255     14      79.00   CHG
Chr1    1118    1119    CHG     10      +       1118    1119    255     10      90.00   CHG
Chr1    1120    1121    CHG     12      -       1120    1121    255     12      92.00   CHG
Chr1    1122    1123    CHG     9       +       1122    1123    255     9       89.00   CHG
Chr1    1124    1125    CHG     14      -       1124    1125    255     14      79.00   CHG
Chr1    1127    1128    CHH     10      +       1127    1128    255     10      90.00   CHH
Chr1    1128    1129    CHH     14      -       1128    1129    255     14      86.00   CHH
Chr1    1138    1139    CHH     11      +       1138    1139    255     11      91.00   CHH
These are the entries in my bed file what I am confused about is I have successfully ran the below command and I got output folders using split by chromosome 
> methyl_bed <- list.files(path=".", pattern="*.bed")
> bedlist <- c()
> for (i in 1:length(methyl_bed)) {
+   beds <- split_by_chromosome(file.path(getwd(), methyl_bed[i]))
+   bedlist[(length(bedlist) + 1)] <- list(beds)
+ }

now after this step what should I do because I tried running following commands but it didn't work what should I do ?
> chrs_list <- unique(str_extract(bedlist,"ch0"))
Warning message:
In stri_extract_first_regex(string, pattern, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing
> chrs_list <- unique(str_extract(bedlist,"Chr0"))
Warning message:
In stri_extract_first_regex(string, pattern, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing
> chrs_list <- unique(str_extract(bedlist,"Chr*"))
Warning message:
In stri_extract_first_regex(string, pattern, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing
> chrs_list <- unique(str_extract(bedlist,"Chr"))
Warning message:
In stri_extract_first_regex(string, pattern, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing
> chr_list <- c(Chr1, Chr2, Chr3, Chr4, Chr5, Chr6, Chr7, Chr8, Chr9, Chr10, Chr11, Chr12)
Error: object 'Chr1' not found
